version: "3.8"

services:
  database:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64/v8
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gis_database
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


